[package]
name = "vaulti-app"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Vaulti desktop/mobile app"

[lib]
name = "vaulti_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
vaulti-core.workspace = true
serde.workspace = true
uuid.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-clipboard-manager = "2"
dirs = "6"
zeroize = "1"
